POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1sdXVra2FpIiwiaWQiOiI1ZGQ4YzRkM2Q5YWIyOTQyYzdhYTcwMmMiLCJpYXQiOjE1NzUyMjI2MzN9.RaQX_2VnFEAAaU6BeGIJKIu6P8yRuBvblU6fD-F36xI

{
  "title": "Understanding Streams in Node.js",
  "author": "Liz Parody",
  "url": "https://nodesource.com/blog/understanding-streams-in-nodejs",
  "likes": 0
}